/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bntrip.vista;

import bntrip.modelo.Modelo;
import bntrip.util.Alojamiento;

/**
 *
 * @author alvaro
 */
public class AlojamientoWindow extends javax.swing.JFrame {
    
    private ControladorAlojamientoWindow  miControlador;
    private Modelo miModelo;
    /**
     * Creates new form AlojamientoWindow
     */
    public AlojamientoWindow(Modelo miModelo) {
        this.miModelo = miModelo;
        miControlador = new ControladorAlojamientoWindow(this, miModelo);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelImages = new javax.swing.JPanel();
        BotonImagen = new javax.swing.JButton();
        jPanelButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 340));
        setMinimumSize(new java.awt.Dimension(410, 340));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelImages.setLayout(new java.awt.GridLayout(1, 1));

        BotonImagen.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room/aloj10.png"))); // NOI18N
        BotonImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonImagen.setLabel("Clik para ver otra");
        BotonImagen.setMaximumSize(new java.awt.Dimension(10000, 10000));
        BotonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImagenActionPerformed(evt);
            }
        });
        jPanelImages.add(BotonImagen);

        jPanel1.add(jPanelImages, java.awt.BorderLayout.CENTER);

        jPanelButtons.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Reservar");
        jPanelButtons.add(jButton1);

        jButton2.setText("Añadir a Lista de deseados");
        jPanelButtons.add(jButton2);

        jPanel1.add(jPanelButtons, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImagenActionPerformed
        Alojamiento alojamiento = miControlador.getAlojamiento();
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(alojamiento.getImagen())));
    }//GEN-LAST:event_BotonImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonImagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelImages;
    // End of variables declaration//GEN-END:variables
}
