/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bntrip.vista;

import bntrip.modelo.Modelo;
import bntrip.util.Alojamiento;

/**
 *
 * @author alvaro
 */
public class AlojamientoWindow extends javax.swing.JFrame {
    
    private ControladorAlojamientoWindow  miControlador;
    private Modelo miModelo;
    private Alojamiento alojamiento;
    /**
     * Creates new form AlojamientoWindow
     */
    public AlojamientoWindow(Modelo miModelo) {
        this.miModelo = miModelo;
        miControlador = new ControladorAlojamientoWindow(this, miModelo);
        alojamiento = miControlador.getAlojamiento();

        initComponents();
        this.setLocationRelativeTo(null);
        
        // Imagen del alojamiento
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(alojamiento.getImagen())));
        // Fecha entrada-salida
        labelIN.setText(miControlador.getFechas().getFechaInicioStr());
        labelOUT.setText((miControlador.getFechas()).getFechaFinStr());
        // Precio
        labelPrecio.setText(Integer.toString((miControlador.getFechas()).getDiasReservados()*(int)alojamiento.getPrecio())+"€");
        // NUmero de huespedes
        labelHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource(getIconoHuesped())));
        setTitle(alojamiento.getCiudad()+" - "+alojamiento.getTipoHabitacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelImages = new javax.swing.JPanel();
        BotonImagen = new javax.swing.JButton();
        jPanelButtons = new javax.swing.JPanel();
        labelHuespedes = new javax.swing.JLabel();
        labelIN = new javax.swing.JLabel();
        labelOUT = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        ButtonReservar = new javax.swing.JButton();
        ButtonDeseado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 340));
        setMinimumSize(new java.awt.Dimension(410, 340));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelImages.setBackground(new java.awt.Color(1, 1, 1));
        jPanelImages.setLayout(new java.awt.GridLayout(1, 1));

        BotonImagen.setBackground(new java.awt.Color(1, 1, 1));
        BotonImagen.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room/aloj10.png"))); // NOI18N
        BotonImagen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotonImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonImagen.setLabel("Clik para ver otra");
        BotonImagen.setMaximumSize(new java.awt.Dimension(10000, 10000));
        BotonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImagenActionPerformed(evt);
            }
        });
        jPanelImages.add(BotonImagen);

        jPanel1.add(jPanelImages, java.awt.BorderLayout.CENTER);

        jPanelButtons.setLayout(new java.awt.GridLayout(1, 0));

        labelHuespedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h4.png"))); // NOI18N
        labelHuespedes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelButtons.add(labelHuespedes);

        labelIN.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        labelIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/in.png"))); // NOI18N
        labelIN.setText("17/Apr");
        jPanelButtons.add(labelIN);

        labelOUT.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        labelOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.png"))); // NOI18N
        labelOUT.setText("17/Apr");
        jPanelButtons.add(labelOUT);

        labelPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/moneda.gif"))); // NOI18N
        labelPrecio.setText("PRECIO");
        jPanelButtons.add(labelPrecio);

        ButtonReservar.setText("Reservar");
        ButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReservarActionPerformed(evt);
            }
        });
        jPanelButtons.add(ButtonReservar);

        ButtonDeseado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseado.png"))); // NOI18N
        jPanelButtons.add(ButtonDeseado);

        jPanel1.add(jPanelButtons, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImagenActionPerformed
        setImagenAlojamiento(alojamiento.getImagen());
        BotonImagen.setText("Click para ver mas fotos");
    }//GEN-LAST:event_BotonImagenActionPerformed

    
    private void ButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReservarActionPerformed
    //System.out.println("Patatuelas");
        Boolean b = miControlador.setReservado(alojamiento);
    //System.out.println("chaskis");
    }//GEN-LAST:event_ButtonReservarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonImagen;
    private javax.swing.JButton ButtonDeseado;
    private javax.swing.JButton ButtonReservar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelImages;
    private javax.swing.JLabel labelHuespedes;
    private javax.swing.JLabel labelIN;
    private javax.swing.JLabel labelOUT;
    private javax.swing.JLabel labelPrecio;
    // End of variables declaration//GEN-END:variables

    private String getIconoHuesped(){
        int numero = miModelo.getHuespedes();
        switch (numero){
            case 1: return ("/images/h1.png");
            case 2: return ("/images/h2.png");
            case 3: return ("/images/h3.png");
            case 4: return ("/images/h4.png");
        }return "/images/h1.png";
    }
    
    public void setImagenAlojamiento(String str){
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(str)));
        BotonImagen.setText("");
    }
}

