/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bntrip.vista;

import bntrip.modelo.Modelo;

/**
 *
 * @author javier
 */
public class LoginWindow extends javax.swing.JFrame {
    private ControladorLoginWindow miControlador;
    private Modelo miModelo;
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow(Modelo miModelo) {
        initComponents();
        miControlador = new ControladorLoginWindow(this, miModelo);
        this.miModelo=miModelo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonGoogle = new javax.swing.JButton();
        botonFb = new javax.swing.JButton();
        botonCorreo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(600, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(new java.awt.Font("Khmer OS System", 1, 70)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOLA");
        jLabel1.setPreferredSize(new java.awt.Dimension(203, 100));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Khmer OS System", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿como quieres acceder?");
        jLabel2.setPreferredSize(new java.awt.Dimension(353, 45));
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1);

        jPanel3.setMinimumSize(new java.awt.Dimension(423, 350));

        botonGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/google.png"))); // NOI18N
        botonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGoogleActionPerformed(evt);
            }
        });
        jPanel3.add(botonGoogle);

        botonFb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        botonFb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFbActionPerformed(evt);
            }
        });
        jPanel3.add(botonFb);

        botonCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jPanel3.add(botonCorreo);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGoogleActionPerformed
        miControlador.setLogeado("Google");
        
    }//GEN-LAST:event_botonGoogleActionPerformed

    private void botonFbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFbActionPerformed
        miControlador.setLogeado("Facebook");
    }//GEN-LAST:event_botonFbActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        miControlador.procesaLogout();
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCorreo;
    private javax.swing.JButton botonFb;
    private javax.swing.JButton botonGoogle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
