/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bntrip.vista;

import bntrip.modelo.Modelo;
import bntrip.util.Alojamiento;
import bntrip.util.Deseado;
import bntrip.util.Reserva;

/**
 *
 * @author javier
 */
public class UserWindow extends javax.swing.JFrame {
    private ControladorUserWindow miControlador;
    private Modelo miModelo;
    
    /**
     * Creates new form UserWindow
     */
    public UserWindow(Modelo miModelo) {
        this.setLocationRelativeTo(null);
        this.miModelo = miModelo;
        miControlador = new ControladorUserWindow(this, miModelo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelConexion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        listaReserva = new java.awt.List();
        labelReserva = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        listaDeseado = new java.awt.List();
        labelDeseado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Area de Usuario");
        setBackground(new java.awt.Color(196, 237, 228));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(400, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(196, 237, 228));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.LINE_END);

        labelConexion.setBackground(new java.awt.Color(196, 237, 228));
        labelConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        labelConexion.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                labelConexionMouseWheelMoved(evt);
            }
        });
        jPanel1.add(labelConexion, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(196, 237, 228));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(196, 237, 228));
        jPanel3.setLayout(new java.awt.BorderLayout());

        listaReserva.setBackground(new java.awt.Color(244, 247, 247));
        listaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaReservaActionPerformed(evt);
            }
        });
        jPanel3.add(listaReserva, java.awt.BorderLayout.CENTER);

        labelReserva.setBackground(new java.awt.Color(196, 237, 228));
        labelReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReserva.setText("Reservas");
        jPanel3.add(labelReserva, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(196, 237, 228));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Eliminar Deseado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, java.awt.BorderLayout.PAGE_END);

        listaDeseado.setBackground(new java.awt.Color(244, 247, 247));
        jPanel4.add(listaDeseado, java.awt.BorderLayout.CENTER);

        labelDeseado.setBackground(new java.awt.Color(196, 237, 228));
        labelDeseado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDeseado.setText("Deseados");
        jPanel4.add(labelDeseado, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        miControlador.procesaLogout();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaReservaActionPerformed

    /**
     * Metodos que se ejecutan cada vez que se abre la ventana.
     * @param evt open window
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargarReservados();
        cargarDeseados();
        
        labelConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource(miControlador.getIconoPerfil())));
        
        if(miControlador.getLoged().equals("Correo")){
            try{
                labelConexion.setText(miModelo.getEmail()); 
                labelConexion.setText(miModelo.getUsuario().getEmail());
            }catch(Exception g){}
            try{ 
               labelConexion.setText(miModelo.getUsuario().getEmail());
               labelConexion.setText(miModelo.getEmail());
            }catch(Exception l){}
            
        }else labelConexion.setText("Conectado con " + miControlador.getLoged());
        
    }//GEN-LAST:event_formWindowOpened

    private void labelConexionMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_labelConexionMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelConexionMouseWheelMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        miControlador.removeDeseado(listaDeseado);
        listaDeseado.removeAll();
        cargarDeseados();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        miControlador.procesaCierre();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelConexion;
    private javax.swing.JLabel labelDeseado;
    private javax.swing.JLabel labelReserva;
    private java.awt.List listaDeseado;
    private java.awt.List listaReserva;
    // End of variables declaration//GEN-END:variables
    
    private void cargarDeseados(){
        miControlador.cargarListaDeseados(listaDeseado);    
    }

    private void cargarReservados(){
        miControlador.cargarListaReservados(listaReserva);
    }
}
