/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bntrip.vista.LoginWindow;

import bntrip.modelo.Modelo;

/**
 * Practica 2 - Interaccion Persona Computadora
 * @date    2017 April.
 * @author  Helguera Lopez, Javier   - javhelg
 * @author  Velasco Gil, Alvaro      - alvvela
 */
public class LoginWindow extends javax.swing.JFrame {
    private ControladorLoginWindow miControlador;
    private Modelo miModelo;
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow(Modelo miModelo) {
        initComponents();
        miControlador = new ControladorLoginWindow(this, miModelo);
        this.miModelo=miModelo;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIniciaSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        botonGoogle = new javax.swing.JButton();
        botonFb = new javax.swing.JButton();
        PanelRegistrate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        PanelIniciaSesion.setLayout(new java.awt.GridLayout(1, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iniciasesion.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelIniciaSesion.add(jLabel3);

        getContentPane().add(PanelIniciaSesion);

        PanelBotones.setMinimumSize(new java.awt.Dimension(450, 350));

        botonGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/google.png"))); // NOI18N
        botonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGoogleActionPerformed(evt);
            }
        });
        PanelBotones.add(botonGoogle);

        botonFb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        botonFb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFbActionPerformed(evt);
            }
        });
        PanelBotones.add(botonFb);

        getContentPane().add(PanelBotones);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registrate_verde.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        PanelRegistrate.add(jLabel1);

        getContentPane().add(PanelRegistrate);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGoogleActionPerformed
        miControlador.setLogeado("Google");
        
    }//GEN-LAST:event_botonGoogleActionPerformed

    private void botonFbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFbActionPerformed
        miControlador.setLogeado("Facebook");
    }//GEN-LAST:event_botonFbActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        miControlador.procesaLogout();
    }//GEN-LAST:event_formWindowClosing

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        miControlador.procesaRegistro();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registrate_verde2.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registrate_verde.png")));
    }//GEN-LAST:event_jLabel1MouseExited

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelIniciaSesion;
    private javax.swing.JPanel PanelRegistrate;
    private javax.swing.JButton botonFb;
    private javax.swing.JButton botonGoogle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
